#[derive(Debug, Clone, PartialEq, PartialOrd)]
pub enum ObjectFlags {
    None,
    SustStr,
    SustInt,
    SustWis,
    SustDex,
    SustCon,
    ProtFear,
    ProtBlind,
    ProtConf,
    ProtStun,
    SlowDigest,
    Feather,
    Regen,
    Telepathy,
    SeeInvis,
    FreeAct,
    HoldLife,
    Impact,
    Blessed,
    BurnsOut,
    TakesFuel,
    NoFuel,
    ImpairHp,
    ImpairMana,
    Afraid,
    NoTeleport,
    Aggravate,
    DrainExp,
    Sticky,
    Fragile,
    Light2,
    Light3,
    Dig1,
    Dig2,
    Dig3,
    Explode,
    TrapImmune,
    Throwing
}

impl ObjectFlags {
    pub fn name(&self) -> &str {
        match self {
            ObjectFlags::None => "",
            ObjectFlags::SustStr => " sStr",
            ObjectFlags::SustInt => " sInt",
            ObjectFlags::SustWis => " sWis",
            ObjectFlags::SustDex => " sDex",
            ObjectFlags::SustCon => " sCon",
            ObjectFlags::ProtFear => "pFear",
            ObjectFlags::ProtBlind => "pBlnd",
            ObjectFlags::ProtConf => "pConf",
            ObjectFlags::ProtStun => "pStun",
            ObjectFlags::SlowDigest => "S.Dig",
            ObjectFlags::Feather => "Feath",
            ObjectFlags::Regen => "Regen",
            ObjectFlags::Telepathy => "  ESP",
            ObjectFlags::SeeInvis => "S.Inv",
            ObjectFlags::FreeAct => "FrAct",
            ObjectFlags::HoldLife => "HLife",
            ObjectFlags::Impact => "Impct",
            ObjectFlags::Blessed => "Bless",
            ObjectFlags::BurnsOut => "BuOut",
            ObjectFlags::TakesFuel => "TFuel",
            ObjectFlags::NoFuel => "NFuel",
            ObjectFlags::ImpairHp => "ImpHP",
            ObjectFlags::ImpairMana => "ImpSP",
            ObjectFlags::Afraid => " Fear",
            ObjectFlags::NoTeleport => "NoTel",
            ObjectFlags::Aggravate => "Aggrv",
            ObjectFlags::DrainExp => "DrExp",
            ObjectFlags::Sticky => "Stick",
            ObjectFlags::Fragile => "Fragl",
            ObjectFlags::Light2 => "Lght2",
            ObjectFlags::Light3 => "Lght3",
            ObjectFlags::Dig1 => "Dig1",
            ObjectFlags::Dig2 => "Dig2",
            ObjectFlags::Dig3 => "Dig3",
            ObjectFlags::Explode => "Expld",
            ObjectFlags::TrapImmune => "TrpIm",
            ObjectFlags::Throwing => "Throw"
        }
    }
}